# Generated by Django 3.2.25 on 2024-10-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_auto_20241010_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
