# Generated by Django 3.2.25 on 2024-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0003_auto_20241017_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
